openapi: 3.0.0
info:
  title: URL Shortener API, Group C - Armstrong, Paul D and Singh Kulkirat
  version: 1.0.0
tags:
  - name: "Authentication"
    description: "Manage user authentication."
  - name: "URL Shortening"
    description: "Manage URL shortening operations."
  - name: "Link Management"
    description: "Manage user links and related operations."
  - name: "Visit Statistics"
    description: "Manage visit statistics for short URLs."

paths:
  /login:
    post:
      tags:
        - "Authentication"
      description: "Login and authenticate a user(LDAP)"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '401':
          description: Unauthorized
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Authentication:
                    type: boolean
                  user:
                    type: string

  /delete_user/{userID}:
    delete:
      tags:
        - "Authentication"
      description: "Delete a user"
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
        '404':
          description: No user found with given userID
        '401':
          description: Unauthorized

  /users/{userID}/link:
    post:
      tags:
        - "URL Shortening"
      description: "Create a new tinyURL for a user"
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                originalLink:
                  type: string
      responses:
        '201':
          description: Created Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortLink:
                    type: string
                  success:
                    type: boolean
                  linkID:
                    type: string
                  userID:
                    type: integer
        '400':
          description: Bad request
        '404':
          description: No user found with given userID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized

  /users/{userID}/links:
    get:
      tags:
        - "Link Management"
      description: "Get all links for a user"
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    originalLink:
                      type: string
                    shortLink:
                      type: string
                    linkID:
                      type: integer
                    userID:
                      type: integer
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found

  /users/{userID}/links/{linkID}:
    get:
      tags:
        - "Link Management"
      description: "Get a specific link for a user"
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: linkID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  originalLink:
                    type: string
                  shortLink:
                    type: string
                  linkID:
                    type: integer
                  userID:
                    type: integer
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found

  /visit/shortURL:
    get:
      tags:
        - "Visit Statistics"
      description: "Visit a shortURL for a user"
      parameters:
        - name: shortURL
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  visitCount:
                    type: integer
                  shortURL:
                    type: string
        '400':
          description: Bad request
        '404':
          description: Not found

  /users/{userID}/delete_link/{linkID}:
    delete:
      tags:
        - "Link Management"
      description: "Delete a link for a user"
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: linkID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
        '404':
          description: Not found
        '500':
          description: Internal Server Error


  /users/{userID}/link/{linkID}:
    put:
      tags:
        - "Link Management"
      description: "Update a shortURL for a user"
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: linkID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shortURL:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  shortURL:
                    type: string
                  long_url:
                    type: string
        '400':
          description: Bad request
        '404':
          description: Not found
